name: "Deploy document files to S3"
on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: Please type "deploy-docs".
env:
  AWS_REGION : "ap-northeast-1"
  ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.ROLE_ARN }}
        role-session-name: actions-role-session
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: x64

    - name: Install sphinx
      run: |
        pip install -U sphinx

    - name: Build html
      run: |
        cd docs && make html

    - name: Sync html to s3
      run: |
        aws s3 sync docs/build/html s3://${{ env.S3_BUCKET }}/docs --delete --quiet
